blank_issues_enabled: true
contact_links:
  - name: The guidelines for the mod list
    url: https://github.com/sneadtristen6/Ruse-Mods/blob/main/GUIDELINES.md
    about: What can go on the list, and what can't.
